development:
  adapter: postgresql
  encoding: unicode
  database: bahai_prayers_development
  pool: 5
  username: bahai_prayers
  password: bahai_prayers
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: bahai_prayers_test
  pool: 5
  username: bahai_prayers
  password: bahai_prayers
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: bahai_prayers_production
  pool: 5
  username: bahai_prayers
  password: bahai_prayers
  host: localhost
