development:
  adapter: sqlite3
  encoding: unicode
  database: db/bahai_prayers_development.sqlite3
  pool: 5
  username: bahai_prayers
  password: bahai_prayers
  host: localhost

test:
  adapter: sqlite3
  encoding: unicode
  database: db/bahai_prayers_test.sqlite3
  pool: 5
  username: bahai_prayers
  password: bahai_prayers
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: bahai_prayers_production
  pool: 5
  username: bahai_prayers
  password: bahai_prayers
  host: localhost
